#!/usr/bin/env bash

iDIR="$HOME/.config/mako/icons"

# Get brightness
get_backlight() {
    max_brightness=$(brightnessctl m)
    current_brightness=$(brightnessctl g)
    brightness_percentage=$(( 100 * current_brightness / (max_brightness) ))
    echo "${brightness_percentage}%"
}

# Get icons
get_icon() {
	backlight="$(brightnessctl g)"
	current="${backlight%%%}"
	if [[ ("$current" -ge "0") && ("$current" -le "52") ]]; then
		icon="$iDIR/brightness-20.png"
	elif [[ ("$current" -ge "52") && ("$current" -le "103") ]]; then
		icon="$iDIR/brightness-40.png"
	elif [[ ("$current" -ge "103") && ("$current" -le "155") ]]; then
		icon="$iDIR/brightness-60.png"
	elif [[ ("$current" -ge "155") && ("$current" -le "207") ]]; then
		icon="$iDIR/brightness-80.png"
	elif [[ ("$current" -ge "180") && ("$current" -le "255") ]]; then
		icon="$iDIR/brightness-100.png"
	fi
}

# Notify
notify_user() {
    brightness_percentage=$(get_backlight)
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$icon" "Brightness : ${brightness_percentage}"
}

# Increase brightness
inc_backlight() {
	brightnessctl set 1%+ && get_icon && notify_user
}

# Decrease brightness
dec_backlight() {
	current_brightness=$(brightnessctl g)
	min_brightness=3840

	if (( current_brightness > min_brightness )); then
		brightnessctl set 1%- && get_icon && notify_user
    fi
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	brightnessctl g
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	get_backlight
fi
