#!/usr/bin/env bash

iDIR="$HOME/.config/mako/icons"

get_backlight() {
    max_brightness=$(brightnessctl m)
    current_brightness=$(brightnessctl g)
    brightness_percentage=$(( 100 * current_brightness / (max_brightness) ))
    echo "${brightness_percentage}%"
}
inc_backlight() {
	brightnessctl set 2%+
}
dec_backlight() {
	current_brightness=$(brightnessctl g)
	min_brightness=3840

	if (( current_brightness > min_brightness )); then
		brightnessctl set 2%-
    fi
}
if [[ "$1" == "--get" ]]; then
	brightnessctl g
elif [[ "$1" == "--inc" ]]; then
	inc_backlight
elif [[ "$1" == "--dec" ]]; then
	dec_backlight
else
	get_backlight
fi